title: 六笔的空间
author: 六笔
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  分享生活，分享技术

twitter_username: xx
github_username:  xx

sass:
    style: compressed